### ISSUE TITLE
Difficulty installing / Wiki outdated?

### ISSUE THREAD

**Issue by walidabualafia** [KudryashevLab/TomoBEAR#30]
### Issue type

Build/Install

### TomoBEAR source

source code (via interactive MATLAB session), standalone binary (using MATLAB libraries)

### TomoBEAR version

v0.5.0

### Computing system

HPC cluster (interactive computing node)

### Issue description

I could not find any resources to properly install the standalone binary. The `install_TomoBEAR.sh` script (mentioned in the wiki) does not seem to exist in any of the releases or even in the repository. Am I looking for the wrong thing?

I tried installing it for MATLAB instead, and I tried executing `runTomoBear("local", "/the/absolute/path/to/ribosome_example.json")`, but Matlab is not recognizing `runTomoBear` as a function. Do you know what might cause this? Not sure where to look.

### Input configuration (JSON) file

N/A. Used default example. I'd be happy to send `defaults.json` by email.

### GPU model and memory

NVIDIA A100-SXM4-80GB

### CUDA version(s)

CUDA11.4

**Comment by ArtsemiY** [comment]
Hi @walidabualafia , thanks for interest!
Unfortunately, we have not produced standalone binaries for the latest versions, since code base refactoring is needed, sorry for that!
However, full MATLAB version is accessible to work with. The ```install_tomoBEAR.sh``` script should be created by yourself and activated, as noted [in the instructions here](https://github.com/KudryashevLab/TomoBEAR/wiki/Installation-and-Setup#clone-specific-version). We haven't put it in the repository since it is supposed to fetch the repository code itself.
Afterwards you need to configure the TomoBEAR ```defaults.json``` [as described here](https://github.com/KudryashevLab/TomoBEAR/wiki/Installation-and-Setup#step-3-configure-tomobear-defaults), which I assume you have done.
Finally, to initialize MATLAB session to be able to use TomoBEAR, you should go to location of TomoBEAR repository in terminal and launch bash script ```run_matlab.sh``` [as described here](https://github.com/KudryashevLab/TomoBEAR/wiki/Installation-and-Setup#matlab-interactive-session). This will open MATLAB session with activated TomoBEAR. You should stay in the same directory (so, TomoBEAR code directory), from where you may launch ```runTomoBEAR(...)``` command (please, note capitalization in the function name).
We also have some video-tutorials with the first one outlining installation procedure, the corresponding links you may find on the main page of the repository.
Hope it clarifies procedure! Otherwise feel free to drop me an email and we will try to solve it.

**Comment by walidabualafia** [comment]
@ArtsemiY,

Thank you so much for the quick response. Any chance TomoBEAR works with one of the newer MATLAB versions?

Additionally, does it accept AreTomo2 instead of AreTomo?

Thank you! :)

**Comment by ArtsemiY** [comment]
Dear @walidabualafia ,

Please, email to me ( artsemi.yushkevich@mdc-berlin.de ) your filled-in ```configurations/defaults.json``` and let's schedule a troubleshooting call via email :)

Best,
Artsemi

**Comment by walidabualafia** [comment]
Hi @ArtsemiY. Thanks for the call! It seems to be working perfectly now.

Best,
Walid
